# Generated by Django 2.2 on 2019-04-13 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('short_name', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=300)),
                ('charter', models.CharField(max_length=1000)),
                ('admins', models.ManyToManyField(related_name='organizations_admined', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='organizations', to='profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='organizations.Organization')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='profiles.Profile')),
            ],
        ),
    ]
